# .github/dependabot.yml

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Location of package.json
    schedule:
      interval: "daily" # Can be "daily", "weekly", "monthly"
    versioning-strategy: "increase" # Options: "increase", "increase-if-necessary", "lockfile-only", "auto"
    allow:
      - dependency-type: "all" # Include both direct and dev dependencies
# .github/dependabot.yml
